[package]
name = "shared"
version = "0.1.0"
authors = ["digifiedquire"]
edition = "2018"


[dependencies]
serde = { version = "1", features = ["derive"] }
num-derive = "0.3.1"
num-traits = "0.2.12"
time = { version = "0.2", default-features = false, features = ["serde"] }

